add_newline = false
format = """\
  $username\
  $kubernetes\
  $directory\
  $git_branch\
  $git_status\
  $character\
  """

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[username]
show_always = true

[kubernetes]
symbol = "ﴱ "
style = "bold blue"
disabled = false
[kubernetes.context_aliases]
"default/default/default" = "home-cluster"

[aws]
disabled = true

[git_branch]
symbol = " "

[git_status]
conflicted = " ~ "
ahead = " ⇡ "
behind = " ⇣ "
staged=" + "
diverged = " ⇕ "
untracked = " ? "
#stashed = " $ "
modified = " ! "
deleted = "  "
renamed = " ➜ "
